apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tutoring\Nucamp\PythonCourses\C3\c3_code\Week2\kubernetes\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Tutoring\Nucamp\PythonCourses\C3\c3_code\Week2\kubernetes\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: itrebligdocker/django_app_docker_compose_nginx:v1
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/static
          name: static-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
status: {}
