apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tutoring\Nucamp\PythonCourses\C3\c3_code\Week2\kubernetes\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Tutoring\Nucamp\PythonCourses\C3\c3_code\Week2\kubernetes\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          value: "False"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin123
        - name: PGADMIN_LISTEN_PORT
          value: "5433"
        image: dpage/pgadmin4:5.2
        imagePullPolicy: ""
        name: pgadmin-container
        ports:
        - containerPort: 5433
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
